services:
  aspen-dev-box:
    image: aspendiscovery/aspen:latest
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-501}
    volumes:
      - "$ASPEN_DOCKER/dockerrun.sh:/entrypoint.sh"
      - "$ASPEN_DOCKER/generate-apache-config.sh:/generate-apache-config.sh"
      - "$ASPEN_CLONE:/usr/local/aspen-discovery"
      - "$ASPEN_DOCKER/site/:/usr/local/aspen-discovery/sites/test.localhostaspen"
      - "$ASPEN_DOCKER/site/conf/crontab_settings.txt:/etc/cron.d/cron"
      - "$ASPEN_DOCKER/aliases:/root/.bashrc"
      - "$ASPEN_DOCKER/tmp:/mnt/tmp"
    ports:
      - "8083:80"
    container_name: containeraspen
    networks:
      - aspen-net
    tty: true
    depends_on:
      aspen-db:
        condition: service_healthy

  aspen-db:
    container_name: aspen-db
    environment:
      - MARIADB_ROOT_PASSWORD=aspen
      - MARIADB_DATABASE=aspen
      - MARIADB_USER=aspensuper
      - MARIADB_PASSWORD=aspensuper
    image: "mariadb:10.11.5"
    volumes:
      - $ASPEN_CLONE/install/aspen.sql:/docker-entrypoint-initdb.d/Aspen-db-startup.sql
    healthcheck:
      interval: 60s
      retries: 10
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
    networks:
      - aspen-net

  solr:
    image: aspendiscovery/solr:latest
    environment:
      - SOLR_PORT=8084
      - SOLR_HOST=solr
    ports:
      - "8084:8084"
    volumes:
      - $ASPEN_CLONE/data_dir_setup/solr7:/opt/solr/server/solr/configsets
    deploy:
      endpoint_mode: dnsrr
    networks:
      - aspen-net
    depends_on:
      - aspen-dev-box
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        init-var-solr
        # Series core
        precreate-core series /opt/solr/server/solr/configsets/series
        cp -r /opt/solr/server/solr/configsets/series/* series

        # Genealogy core
        precreate-core genealogy /opt/solr/server/solr/configsets/genealogy
        cp -r /opt/solr/server/solr/configsets/genealogy/* genealogy

        # Grouped Works v2 core
        precreate-core grouped_works_v2 /opt/solr/server/solr/configsets/grouped_works_v2
        cp -r /opt/solr/server/solr/configsets/grouped_works_v2/* grouped_works_v2

        # Lists core
        precreate-core lists /opt/solr/server/solr/configsets/lists
        cp -r /opt/solr/server/solr/configsets/lists/* lists

        # Course Reserves core
        precreate-core course_reserves /opt/solr/server/solr/configsets/course_reserves
        cp -r /opt/solr/server/solr/configsets/course_reserves/* course_reserves

        # Open Archives core
        precreate-core open_archives /opt/solr/server/solr/configsets/open_archives
        cp -r /opt/solr/server/solr/configsets/open_archives/* open_archives

        # Website Pages core
        precreate-core website_pages /opt/solr/server/solr/configsets/website_pages
        cp -r /opt/solr/server/solr/configsets/website_pages/* website_pages

        # Events core
        precreate-core events /opt/solr/server/solr/configsets/events
        cp -r /opt/solr/server/solr/configsets/events/* events


        chown -R solr:solr /var/solr
        runuser -u solr -- solr-foreground


networks:
  aspen-net:
    name: aspen-net
    driver: bridge
