services:
  aspen-dev-box:
    image: aspendiscovery/aspen:latest
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-501}
    volumes:
      - "$ASPEN_DOCKER/dockerrun.sh:/entrypoint.sh"
      - "$ASPEN_DOCKER/generate-apache-config.sh:/generate-apache-config.sh"
      - "$ASPEN_CLONE:/usr/local/aspen-discovery"
      - "$ASPEN_DOCKER/site/:/usr/local/aspen-discovery/sites/test.localhostaspen"
      - "$ASPEN_DOCKER/site/conf/crontab_settings.txt:/etc/cron.d/cron"
      - "$ASPEN_DOCKER/aliases:/root/.bashrc"
      - "$ASPEN_DOCKER/tmp:/mnt/tmp"
    ports:
      - "8083:80"
    container_name: containeraspen
    networks:
      - aspen-net
    tty: true
    depends_on:
      aspen-db:
        condition: service_healthy

  aspen-db:
    container_name: aspen-db
    environment:
      - MARIADB_ROOT_PASSWORD=aspen
      - MARIADB_DATABASE=aspen
      - MARIADB_USER=aspensuper
      - MARIADB_PASSWORD=aspensuper
    image: "mariadb:10.11.5"
    volumes:
      - $ASPEN_CLONE/install/aspen.sql:/docker-entrypoint-initdb.d/Aspen-db-startup.sql
    healthcheck:
      interval: 60s
      retries: 10
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
    networks:
      - aspen-net

  solr:
    image: aspendiscovery/solr:latest
    user: "8983:8983"
    environment:
      - SOLR_PORT=8084
      - SOLR_HOST=solr
    ports:
      - "8084:8084"
    deploy:
      endpoint_mode: dnsrr
    networks:
      - aspen-net
    depends_on:
      - aspen-dev-box

networks:
  aspen-net:
    name: aspen-net
    driver: bridge
