version: '3.8'

services:
  aspen-dev-box:
    volumes:
      - "$ASPEN_DOCKER/dockerrun.sh:/entrypoint.sh"
      - "$ASPEN_CLONE:/usr/local/aspen-discovery"
      - "$ASPEN_DOCKER/site/ktd/:/usr/local/aspen-discovery/sites/test.localhostaspen"
      - "$ASPEN_DOCKER/site/ktd/conf/crontab_settings.txt:/etc/cron.d/cron"
      - "$ASPEN_DOCKER/aliases:/root/.bashrc"
    networks:
      - aspen-net
      - kohanet

  aspen-db:
    environment:
      - KOHA_STACK=${KOHA_STACK:-kohadev}
    volumes:
      - $ASPEN_DOCKER/database_start_scripts/ktd/setup_koha_connection.sh:/docker-entrypoint-initdb.d/zzz-setup_koha_connection.sh
    networks:
      - aspen-net
      - kohanet

networks:
  aspen-net:
    name: aspen-net
    driver: bridge
  kohanet:
    external: true
    name: ${KOHA_STACK:-kohadev}_kohanet 
