version: '3.8'

services:
  aspen-dev-box:
    volumes:
      - "$ASPEN_DOCKER/dockerrun.sh:/entrypoint.sh"
      - "$ASPEN_CLONE:/usr/local/aspen-discovery"
      - "$ASPEN_DOCKER/aliases:/root/.bashrc"
    networks:
      - aspen-net
      - kohanet

  aspen-db:
    networks:
      - aspen-net
      - kohanet

networks:
  aspen-net:
    driver: bridge
  kohanet:
    external: true
    name: ${KOHA_STACK:-kohadev}_kohanet 
